# -*- coding: utf-8 -*-
"""UESSAY0001 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z11ECSI_CiSnsxj1fXpEY6PQVyMmfKWh
"""

#THIS ONE FIRSTLY
import pandas as pd
df=pd.read_excel("WaterQuality01.xlsx")#lire le fichier excel
#print(df.head())   # qfficher les 5 premiers lignes
DF=pd.DataFrame([[30,1],[90,3],[3,4],[5,5],[1000,4],[20,2],[5,2],[0.5,5],[50,5],[0.5,5],[5,5]],columns=["Si","wi"])
#DF rendre le petit tableau au dataframe
Lbig=[]
i=3
H=0
for j in DF.itertuples(): #iterer sur les colones et les lignes du DF
        W =(j.wi)/(DF["wi"].sum()+4) # calculer le W
        for P in df[list(df.columns)[i:-1]]:
                #iterer sur une list qui contient juste les noms des colonnes df
                L0=[]
                for C in df[P]:#iterer sur chaque ligne d'un colonne
                        Q =(C/j.Si)*100 #calcul du Q
                        if j.Si==DF["Si"][H] and P==list(df.columns)[i]:
                            #sert a rassembler les SI du chaque colone
                            L0.append(W*Q)
                if C == df[P].iloc[-1]:#condition pour s'arreter la deuxieme boucle for
                    i+=1 #changer a la colonne suivante
                    H+=1
                    Lbig.append(L0)
                    #print(L0)
                    break

L1=[]
for o in df["pH"]:#iterer sur les C du ph
    SIpH=(4/45)*((o-8.5)/(6.5-8.5))
    L1.append(SIpH)
Lbig.append(L1)
data=pd.DataFrame(Lbig)#,index=["SI^T°C",]
wawq=[]
for Y in range(len(df)):
    Z=data[Y].sum()
    wawq.append(Z)
new_one=df.assign(WAWQI=wawq)#ajouter la collonne WAWQI

new_one["QUALITY"]=["EXELENT Water" if s<50  else "GOOD Water"if s<=100 and s>=50 else"POOR Water"if s<=200 and s>=101 else "VERY POOR"if s<=300 and s>=201 else "Unsuitable for drinking"for s in new_one["WAWQI"]]
# ajouter la colonne quality avec les descriptions
new_one

#Second
import pandas as pd
df1=pd.read_excel("WaterQuality01.xlsx")
DF1=pd.DataFrame([[30,1],[90,3],[3,4],[5,5],[1000,4],[20,2],[5,2],[0.5,5],[50,5],[0.5,5],[5,5]],columns=["Si","wi"])
Lbig1=[]
i=3
H=0
for j in DF1.itertuples(): #iter DF1 j.Si
        W =(j.wi)/(DF1["wi"].sum()+4)
        for P in df1[list(df1.columns)[i:-1]]:#iterer sur une list qui contient juste les noms des colonnes df1
                L00=[]
                for C in df1[P]:
                        Q =(C/j.Si)*100
                        if j.wi==DF1["wi"][H] and P==list(df1.columns)[i]:
                            L00.append(Q**W)#LIST L00 CONTIENT LES SI de chaque parametre
                if C == df1[P].iloc[-1]:
                    i+=1
                    H+=1
                    Lbig1.append(L00)
                    break

L01=[]
for o in df1["pH"]:
    A=((o-8.5)/(6.5-8.5))**(4/45)
    L01.append(A)
#print(L01)
Lbig1.append(L01)#big list contient des petites listes L00
data1=pd.DataFrame(Lbig1)
wgwq1=[]
for Y in range(len(df1)):
                Z=data1[Y].prod()
                wgwq1.append(Z)
new_two=df.assign(WGWQI=wgwq1)
#print(new_two)
new_two["QUALITY"]=["EXELENT" if s<=100 and s>=90  else "GOOD"if s<=89 and s>=70 else"MEDIUM"if s<=69 and s>=50 else " Bad"if s<=49 and s>=25 else "Very Bad" if s<=24 and s>=0 else None for s in new_two["WGWQI"]]
new_two

#thirdly
import pandas as pd
from math import sqrt
df2=pd.read_excel("WaterQuality01.xlsx")
df2.drop(columns=["DCO","CONDUCTIVITE","MES","TURBIDITE","NITRITE"],inplace=True)#Effacer ces colonnes du df2
#print(df2.head(3))
DF2=pd.DataFrame([[30,1],[3,4],[5,5],[50,5],[0.5,5],[5,5],[594,5]],columns=["Si","wi"])
Lbig10=[]
i=3
H=0
for j in DF2.itertuples(): #iter DF j.Si
        W =(j.wi)/(DF2["wi"].sum()+4)
        for P in df2[list(df2.columns)[i:]]:
                L10=[]
                for C in df2[P]:
                        Q =(C/j.Si)*100
                        SI=(Q*W)**2
                        L10.append(SI)
                if C == df2[P].iloc[-1]:
                            i+=1
                            H+=1
                            Lbig10.append(L10)
                            break

L10=[]
for o in df2["pH"]:#iterer sur les valeurs  du ph

    A=((o-8.5)/(6.5-8.5))*(4/45)#calculer SI ph
    L10.append(A)
Lbig10.append(L10)
#print(Lbig10)
data10=pd.DataFrame(Lbig10)
#print(data10)
owqi=[]
for Y in range(len(df2)): #iterer les element du data10
        #print(1)
        Z=sqrt(8/(1/data10[Y]).sum())
        owqi.append(Z)

new_tree=df2.assign(OWQI=owqi)
new_tree["QUALITY"]=["EXELENT" if s<=100 and s>=90  else "GOOD"if s<=89 and s>=85 else"FAIR"if s<=84 and s>=80 else " POOR"if s<=79 and s>=60 else "Very POOR" for s in new_tree["OWQI"]]
new_tree

#THE LAAAASSSTT ONE
df3=pd.read_excel("WaterQuality01.xlsx")
df3.drop(df3.iloc[:,2:],inplace=True,axis=1)
df3_one=df3.assign(WAWQI=wawq)#ajouter la colonne WAWQI
df3_one["QUALITYWAWQI"]=["EXELENT Water" if s<50  else "GOOD Water"if s<=100 and s>=50 else"POOR Water"if s<=200 and s>=101 else "VERY POOR"if s<=300 and s>=201 else "Unsuitable for drinking"for s in df3_one["WAWQI"]]
df3_two=df3_one.assign(WGWQI=wgwq1)#ajouter la colonne WGWQ1
df3_two["QUALITYWGWQI"]=["EXELENT" if s<=100 and s>=90  else "GOOD"if s<=89 and s>=70 else"MEDIUM"if s<=69 and s>=50 else " Bad"if s<=49 and s>=25 else "Very Bad" if s<=24 and s>=0 else None for s in df3_two["WGWQI"]]
df3_tree=df3_two.assign(OWQI=owqi)#ajouter la colonne OWQI
df3_tree["QUALITYOWQI"]=["EXELENT" if s<=100 and s>=90  else "GOOD"if s<=89 and s>=85 else"FAIR"if s<=84 and s>=80 else " POOR"if s<=79 and s>=60 else "Very POOR" for s in df3_tree["OWQI"]]
df3_tree

